template: |
  # Surge Version $INPUT_VERSION

  $CHANGES

categories:
  - title: 'New Features'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
