name: branch

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      TEMPLATE_TYPE: lib
      IS_PIPELINE: 'true'
      NAMESPACE: gears-arch
      NAMESPACE_AIRLOCK_HOST: https://gateway.quark-airlock.dlas1.ucloud.int/gears-tools
      NAMESPACE_AIRLOCK_HASH: ${{ secrets.AIRLOCK_HASH }}
      NAMESPACE_AIRLOCK_NAME: dev
      PIPELINE_NAME: surge-kafka-streams.lib
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Scala
        uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.8
      - name: test
        run: 'fnd update && fnd tanagra:build:test'
