name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Verify Tag is on a protected branch
        run: exit 1
        if: ${{ steps.extract_branch.outputs.branch }} != main && ${{ steps.extract_branch.outputs.branch }} != 0.4-compat
      - uses: release-drafter/release-drafter@v5
        id: draft_release
        name: Draft Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Surge ${{ github.ref }}
          body: ${{ steps.draft_release.outputs.body }}
          draft: false
          prerelease: false
