name: surge-kafka-streams-ci
'on':
  push:
    branches-ignore:
      - main
      - 0.4-compat
jobs:
  build:
    env:
      TEMPLATE_TYPE: lib
      IS_PIPELINE: 'true'
      CMD_OPTS: ''
      SMALL_TEST_CMD_OPTS: SmallTests
      MEDIUM_TEST_CMD_OPTS: MediumTests
      CONTRACT_TEST_CMD_OPTS: ContractTests
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      NAMESPACE: ge-incubator
      NAMESPACE_AIRLOCK_HOST: 'https://gateway.quark-airlock.dlas1.ucloud.int/tcxadoption'
      NAMESPACE_AIRLOCK_HASH: '${{ secrets.AIRLOCK_HASH }}'
      NAMESPACE_AIRLOCK_NAME: prod
      PROJECT_NAME: surge-kafka-streams
      PIPELINE_NAME: surge-kafka-streams
      PROJECT_DIR: ''
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: update fnd
        run: fnd update
      - name: started
        run: 'fnd tanagra:status:report --pipeline_status=STARTED'
      - name: package
        run: |-
          fnd tanagra:build:package \
            --environment_json=
      - name: test
        run: |-
          fnd tanagra:build:test \
            --cmd_opts=$SMALL_TEST_CMD_OPTS \
            --environment_json=
      - name: succeeded
        run: 'fnd tanagra:status:report --pipeline_status=SUCCEEDED'
        if: '${{ success() }}'
      - name: failed
        run: 'fnd tanagra:status:report --pipeline_status=FAILED'
        if: '${{failure() || cancelled()}}'
